name: env

channels:
  - conda-forge

dependencies:
  - python>=3.10
  - notebook
  - ipywidgets
  - numpy
  - matplotlib
  - imageio
  - moviepy
  - scikit-learn
  - wandb
  - pip>=23
  - pip:
    - autoroot
    - autorootcwd